/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Class.define("com.zenesis.qx.remote.test.serialisation.G", {
  "extend" : com.zenesis.qx.remote.test.serialisation.F,
  "construct" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    args.unshift(arguments);
    this.base.apply(this, args);
    this.initialiseProxy();
 },
  "properties" : {
    "stringProperty" : {
      "@" : [ new com.zenesis.qx.remote.annotations.Property().set({"readOnly":true}) ],
      "nullable" : true,
      "apply" : "_applyStringProperty",
      "check" : "String",
      "event" : "changeStringProperty"
    }
  },
  "members" : {
    "_applyStringProperty" : function(value, oldValue, name) {
    this._applyProperty("stringProperty", value, oldValue, name);
 },
    "getStringPropertyAsync" : function() {
    return qx.Promise.resolve(this.getStringProperty()).bind(this);
 }
  },
  "defer" : function(clazz) {
    clazz.$$eventMeta = {};
    clazz.$$methodMeta = {};
    com.zenesis.qx.remote.MProxy.deferredClassInitialisation(clazz);
    qx.lang.Object.mergeWith(clazz.$$properties.stringProperty, {"onDemand":false,"isServer":true,"readOnly":true,"sync":"queue","nativeKeyType":true});
    clazz.$$eventMeta.changeStringProperty = {"isServer":true,"isProperty":true};
 }
});
