/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Interface.define("com.zenesis.qx.remote.test.serialisation.IB", {
  "extend" : [ com.zenesis.qx.remote.test.serialisation.IA ]
});
