/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Class.define("com.zenesis.qx.remote.test.serialisation.TestMethodConflict", {
  "extend" : qx.core.Object,
  "implement" : [ com.zenesis.qx.remote.test.serialisation.ITestMethodConflict1, com.zenesis.qx.remote.test.serialisation.ITestMethodConflict2 ],
  "construct" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    args.unshift(arguments);
    this.base.apply(this, args);
    this.initialiseProxy();
 },
  "defer" : function(clazz) {
    clazz.$$eventMeta = {};
    clazz.$$methodMeta = {};
    com.zenesis.qx.remote.MProxy.deferredClassInitialisation(clazz);
 }
});
