/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Interface.define("com.zenesis.qx.remote.test.properties.ITestArrays", {
  "members" : {
    "testObjectArray" : function() {
    
 },
    "testObjectArrayList" : function() {
    
 },
    "testScalarArray" : function() {
    
 },
    "testScalarArrayList" : function() {
    
 }
  }
});
