/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Interface.define("com.zenesis.qx.remote.test.properties.ITestProperties", {
  "members" : {
    "triggerSomeEvent" : function() {
    
 },
    "getChangeLog" : function() {
    
 }
  }
});
