/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Class.define("com.zenesis.qx.remote.test.properties.TestExceptions", {
  "extend" : qx.core.Object,
  "implement" : [ com.zenesis.qx.remote.test.properties.ITestExceptions ],
  "construct" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    args.unshift(arguments);
    this.base.apply(this, args);
    this.initialiseProxy();
 },
  "properties" : {
    "string" : {
      "nullable" : true,
      "apply":"_applyString",
      "check":"String",
      "event":"changeString"
    }
  },
  "members" : {
    "_applyString" : function(value, oldValue, name) {
    this._applyProperty("string", value, oldValue, name);
 },
    "getStringAsync" : function() {
    return qx.Promise.resolve(this.getString()).bind(this);
 }
  },
  "defer" : function(clazz) {
    clazz.$$eventMeta = {};
    clazz.$$methodMeta = {};
    com.zenesis.qx.remote.MProxy.deferredClassInitialisation(clazz);
    qx.lang.Object.mergeWith(clazz.$$properties.string, {
      "onDemand" : false,
      "isServer" : true,
      "readOnly" : false,
      "sync":"immediate",
      "nativeKeyType" : true
    });
    clazz.$$eventMeta.changeString = {
      "isServer" : true,
      "isProperty" : true
    };
 }
});
