/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Interface.define("com.zenesis.qx.remote.LogEntrySink", {
  "members" : {
    "addLogEntries" : function() {
    
 }
  }
});
