/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Interface.define("com.zenesis.qx.remote.test.simple.IMainTests", {
  "members" : {
    "verifyTestScalars" : function() {
    
 },
    "getTestArrays" : function() {
    
 },
    "getTestScalars" : function() {
    
 },
    "getTestExceptions" : function() {
    
 }
  }
});
