/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 */

qx.Interface.define("com.zenesis.qx.remote.test.simple.ITestScalars", {
  "members" : {
    "getSixPointSeven" : function() {
    
 },
    "getFourtyThree" : function() {
    
 },
    "getHelloWorld" : function() {
    
 },
    "addUp" : function() {
    
 },
    "getNames" : function() {
    
 }
  }
});
