/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 * @use(com.zenesis.qx.remote.test.simple.TestObserver$Inner)
 * @use(com.zenesis.qx.remote.test.simple.TestObserver$StaticInner2)
 * @use(com.zenesis.qx.remote.test.simple.TestObserver$StaticInner1)
 */

qx.Class.define("com.zenesis.qx.remote.test.simple.TestObserver", {
  "extend" : qx.core.Object,
  "construct" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    args.unshift(arguments);
    this.base.apply(this, args);
    this.initialiseProxy();
 },
  "members" : {
    "createInner" : function() {
    return this._callServer("createInner", qx.lang.Array.fromArguments(arguments));
 },
    "createStaticInner2" : function() {
    return this._callServer("createStaticInner2", qx.lang.Array.fromArguments(arguments));
 },
    "createStaticInner1" : function() {
    return this._callServer("createStaticInner1", qx.lang.Array.fromArguments(arguments));
 },
    "createStaticInner2Async" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    return new qx.Promise(function(resolve, reject) {
      args.push(function() {
        resolve.apply(this, qx.lang.Array.fromArguments(arguments));
      });
      this._callServer("createStaticInner2", args);
    }, this);
 },
    "createInnerAsync" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    return new qx.Promise(function(resolve, reject) {
      args.push(function() {
        resolve.apply(this, qx.lang.Array.fromArguments(arguments));
      });
      this._callServer("createInner", args);
    }, this);
 },
    "createStaticInner1Async" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    return new qx.Promise(function(resolve, reject) {
      args.push(function() {
        resolve.apply(this, qx.lang.Array.fromArguments(arguments));
      });
      this._callServer("createStaticInner1", args);
    }, this);
 }
  },
  "defer" : function(clazz) {
    clazz.$$eventMeta = {};
    clazz.$$methodMeta = {};
    com.zenesis.qx.remote.MProxy.deferredClassInitialisation(clazz);
    clazz.$$methodMeta.createInner = {
      "isServer" : true,
      "returnType":"com.zenesis.qx.remote.test.simple.TestObserver$Inner"
    };
    clazz.$$methodMeta.createStaticInner1 = {
      "isServer" : true,
      "returnType":"com.zenesis.qx.remote.test.simple.TestObserver$StaticInner1"
    };
    clazz.$$methodMeta.createStaticInner2 = {
      "isServer" : true,
      "returnType":"com.zenesis.qx.remote.test.simple.TestObserver$StaticInner2"
    };
 }
});
