/**
 * Class generated by Qoxodoo Server Objects com.zenesis.qx.remote.ClassWriter
 * 
 * @use(com.zenesis.qx.remote.collections.ArrayList)
 */

qx.Class.define("com.zenesis.qx.remote.test.simple.TestObserver$Inner", {
  "extend" : qx.core.Object,
  "construct" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    args.unshift(arguments);
    this.base.apply(this, args);
    this.initialiseProxy();
 },
  "properties" : {
    "dirty" : {
      "init" : false,
      "nullable" : false,
      "apply":"_applyDirty",
      "check":"Boolean",
      "event":"changeDirty"
    },
    "simpleArray" : {
      "@" : [ new com.zenesis.qx.remote.annotations.Property().set({
  "componentTypeName":"String"
}) ],
      "transform":"__transformSimpleArray",
      "nullable" : true,
      "apply":"_applySimpleArray",
      "check":"qx.data.Array",
      "event":"changeSimpleArray"
    },
    "qsoArrayList" : {
      "@" : [ new com.zenesis.qx.remote.annotations.Property().set({
  "componentTypeName":"String"
}) ],
      "transform":"__transformQsoArrayList",
      "nullable" : true,
      "apply":"_applyQsoArrayList",
      "check":"com.zenesis.qx.remote.collections.ArrayList",
      "event":"changeQsoArrayList"
    },
    "someValue" : {
      "nullable" : true,
      "apply":"_applySomeValue",
      "check":"String",
      "event":"changeSomeValue"
    }
  },
  "members" : {
    "_applyQsoArrayList" : function(value, oldValue, name) {
    this._applyProperty("qsoArrayList", value, oldValue, name);
 },
    "_applySomeValue" : function(value, oldValue, name) {
    this._applyProperty("someValue", value, oldValue, name);
 },
    "_applyDirty" : function(value, oldValue, name) {
    this._applyProperty("dirty", value, oldValue, name);
 },
    "doStuff" : function() {
    return this._callServer("doStuff", qx.lang.Array.fromArguments(arguments));
 },
    "__transformQsoArrayList" : function(value) {
    return com.zenesis.qx.remote.MProxy.transformToDataArray(value, com.zenesis.qx.remote.collections.ArrayList);
 },
    "getSomeValueAsync" : function() {
    return qx.Promise.resolve(this.getSomeValue()).bind(this);
 },
    "getSimpleArrayAsync" : function() {
    return qx.Promise.resolve(this.getSimpleArray()).bind(this);
 },
    "_applySimpleArray" : function(value, oldValue, name) {
    this._applyProperty("simpleArray", value, oldValue, name);
 },
    "__transformSimpleArray" : function(value) {
    return com.zenesis.qx.remote.MProxy.transformToDataArray(value, qx.data.Array);
 },
    "getQsoArrayListAsync" : function() {
    return qx.Promise.resolve(this.getQsoArrayList()).bind(this);
 },
    "doStuffAsync" : function() {
    var args = qx.lang.Array.fromArguments(arguments);
    return new qx.Promise(function(resolve, reject) {
      args.push(function() {
        resolve.apply(this, qx.lang.Array.fromArguments(arguments));
      });
      this._callServer("doStuff", args);
    }, this);
 },
    "getDirtyAsync" : function() {
    return qx.Promise.resolve(this.getDirty()).bind(this);
 }
  },
  "defer" : function(clazz) {
    clazz.$$eventMeta = {};
    clazz.$$methodMeta = {};
    com.zenesis.qx.remote.MProxy.deferredClassInitialisation(clazz);
    clazz.$$methodMeta.doStuff = {
      "isServer" : true
    };
    qx.lang.Object.mergeWith(clazz.$$properties.dirty, {
      "onDemand" : false,
      "isServer" : true,
      "readOnly" : false,
      "sync":"queue",
      "nativeKeyType" : true
    });
    qx.lang.Object.mergeWith(clazz.$$properties.simpleArray, {
      "onDemand" : false,
      "isServer" : true,
      "array":"wrap",
      "readOnly" : false,
      "sync":"queue",
      "nativeKeyType" : true
    });
    qx.lang.Object.mergeWith(clazz.$$properties.qsoArrayList, {
      "onDemand" : false,
      "isServer" : true,
      "arrayClass":"com.zenesis.qx.remote.collections.ArrayList",
      "array":"wrap",
      "readOnly" : false,
      "sync":"queue",
      "nativeKeyType" : true
    });
    qx.lang.Object.mergeWith(clazz.$$properties.someValue, {
      "onDemand" : false,
      "isServer" : true,
      "readOnly" : false,
      "sync":"queue",
      "nativeKeyType" : true
    });
    clazz.$$eventMeta.changeDirty = {
      "isServer" : true,
      "isProperty" : true
    };
    clazz.$$eventMeta.changeSomeValue = {
      "isServer" : true,
      "isProperty" : true
    };
    clazz.$$eventMeta.changeSimpleArray = {
      "isServer" : true,
      "isProperty" : true
    };
    clazz.$$eventMeta.changeQsoArrayList = {
      "isServer" : true,
      "isProperty" : true
    };
 }
});
